In [4]:
from google.colab import drive
drive.mount('/content/gdrive/')


Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("gdrive/MyDrive/dataClientAssu.csv")
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 55.4 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LinearRegression

In [8]:
dataC= data["charges"]
dataC

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [9]:
data['sex'].replace(['male','female'],[0,1],inplace= True) #remplace les variables catégorielles en numérique
data['smoker'].replace(['no','yes'],[0,1],inplace= True)#
data['region'].replace(['northeast','southeast','southwest','northwest'],[0,1,2,3],inplace= True)

In [10]:
Y=data["charges"]
X= data.drop("charges",axis=1)
print(X)
print(Y)

      age  sex     bmi  children  smoker  region
0      19    1  27.900         0       1       2
1      18    0  33.770         1       0       1
2      28    0  33.000         3       0       1
3      33    0  22.705         0       0       3
4      32    0  28.880         0       0       3
...   ...  ...     ...       ...     ...     ...
1333   50    0  30.970         3       0       3
1334   18    1  31.920         0       0       0
1335   18    1  36.850         0       0       1
1336   21    1  25.800         0       0       2
1337   61    1  29.070         0       1       3

[1338 rows x 6 columns]
0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64


In [11]:
model = LinearRegression()
model.fit(X,Y) #entrainement sur le modèle
print("le modèle est fiable à ",model.score(X,Y)*100,"%")


le modèle est fiable à  74.980239308991 %


In [12]:
def moncredit(model,age=23,sex=0,bmi=19.4,children=0,smoker=0,region=0):
  x=np.array([age,sex,bmi,children,smoker,region]).reshape(1,6)
  print(model.predict(x))
 

In [13]:
print("la predictions des charges correspondent à :")
Y_predict=moncredit(model)


la predictions des charges correspondent à :
[155.37618221]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


Le resultat est pas conforme, la prediction est fausse

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test , Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

print('Train set', X_train.shape)
print('Test set', X_test.shape)

Train set (1070, 6)
Test set (268, 6)


In [16]:
model.fit(X_train, Y_train)
print('Train score:', model.score(X_train,Y_train))
print('Test score:', model.score(X_test,Y_test))

Train score: 0.7565493550000602
Test score: 0.7167504114891567


In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(LinearRegression(), X_train,Y_train, cv=5, scoring ='accuracy').mean()

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:776: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_scorer.py", line 107, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_scorer.py", line 268, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pr

nan

### Dummy modèle

In [19]:
from sklearn.dummy import DummyRegressor

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, shuffle=True, train_size=0.8, random_state=42)
dummy = DummyRegressor()
X_train.head()
dummy.fit(X_train, Y_train)
dummy.score(X_test, Y_test)

-0.0009192486886582252

In [21]:
from sklearn.model_selection import KFold

In [22]:
cv= KFold(5, random_state=0, shuffle=True)
cross_val_score(LinearRegression(),X,Y, cv =cv)

array([0.79806191, 0.77752613, 0.65595805, 0.75180281, 0.71463349])

In [23]:
cross_val_score(LinearRegression(), X,Y,cv=3)

array([0.7501241 , 0.75436919, 0.72742911])

In [ ]:
# err_hist= np.abs(Y-Y_predict )
# plt.hist(err_hist, bins=50)
# plt.show()

Preprossecing (transformation des données)


In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler= MinMaxScaler()
scaler.fit_transform(X)

array([[0.02173913, 1.        , 0.3212268 , 0.        , 1.        ,
        0.66666667],
       [0.        , 0.        , 0.47914985, 0.2       , 0.        ,
        0.33333333],
       [0.2173913 , 0.        , 0.45843422, 0.6       , 0.        ,
        0.33333333],
       ...,
       [0.        , 1.        , 0.56201238, 0.        , 0.        ,
        0.33333333],
       [0.06521739, 1.        , 0.26472962, 0.        , 0.        ,
        0.66666667],
       [0.93478261, 1.        , 0.35270379, 0.        , 1.        ,
        1.        ]])

In [26]:
model.fit(X_train,Y_train)

LinearRegression()

Version avec Pipeline


In [27]:
from sklearn import pipeline

In [37]:
 from sklearn.pipeline import make_pipeline
 from sklearn.preprocessing import StandardScaler
 #from sklearn.preprocessing import SimpleImputer
 from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [29]:
y= data['charges'] # Je prend la colonne des charges de monn dataset
x= data.drop('charges', axis = 1) # je prend toute les colonnes de mon dataset excepté la colonne charges
#Cela me permet d'avoir deux dataset et entrainer les paramètres (age,smoker,children,sex,region) sur la valeur charges

In [30]:
numerical_features = ['age','bmi']
categorical_features =  ['children','sex','region']

In [39]:
numerical_pipeline = make_pipeline(SimpleImputer(),StandardScaler())

categorical_pipeline = make_pipeline(SimpleImputer(strategy= 'most_frequent'),OneHotEncoder())

numerical_pipeline
categorical_pipeline

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('onehotencoder', OneHotEncoder())])

In [ ]:
mae_column_transformer((numerical_pipeline, numerical_features),
                       (categorical_pipeline, categorical_features))